name: 'Run script (dev)'

on:
  push:
    branches:
      - master

  # schedule:
  #   - cron: '5 16 * * *' # Every day at 1605 UTC (0005 SGT)

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: yarn install

      - name: Build
        run: yarn build

      - name: Run script
        run: yarn dev:start
        env:
          TEST_BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
          TEST_CHANNEL_NAME: ${{ secrets.TEST_CHANNEL_NAME }}
