name: 'Run script (dev)'

on:
  push:
    branches:
      - master

  schedule:
    - cron: '*/5 * * * *' # Every day at 1625 UTC (0025 SGT)

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: yarn install

      - name: Run script
        run: yarn start
        env:
          BOT_TOKEN: ${{ secrets.TEST_BOT_TOKEN }}
          CHANNEL_NAME: ${{ secrets.TEST_CHANNEL_NAME }}
