name: 'Run script (prod)'

on:
  schedule:
    - cron: '57 21 * * *' # Every day at 2157 UTC (0557 SGT)

  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      
      - name: Install dependencies
        run: yarn install

      - name: Run script
        run: yarn start
        env:
          NODE_ENV: production
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHANNEL_NAME: ${{ secrets.CHANNEL_NAME }}
